### ISSUE TITLE
Kerberos support

### ISSUE THREAD

**Issue by zygm0nt** [spotify/snakebite#59]
Hi, 

I'd like to implement Kerberos support for snakebite. Been looking through documentation, but since I don't know snakebite codebase that well, could you point me in the right direction - where should this additional auth be implemented?

Or perhaps there is already some effort at implementing this feature?

**Comment by beugley** [comment]
I am also interested in this enhancement.  Have you made any progress or need help?

**Comment by hcoyote** [comment]
Bump.  Any update?

**Comment by wouterdebie** [comment]
Sorry all, no updates on this..

**Comment by bolkedebruin** [comment]
Ha Wouter,

I just finished writing an initial implementation of SASL+GSSAPI authentication. You can find it https://github.com/bolkedebruin/snakebite .  It was tested against CDH 5.3. 

No quality of protection implemented yet and you might find some rough edges. Let me know if you want some updates or a pull request.

**Comment by bolkedebruin** [comment]
O and I should mention I guess that I did not test against a non secure setup ;-).

**Comment by oflebbe** [comment]
The kerberos patch from https://github.com/bolkedebruin/snakebite works wonderful with my apache bigtop derived installation! +1

**Comment by bolkedebruin** [comment]
@wouterdebie has the enthusiasm for this patch faded? I have created pull request #153 for this.

**Comment by wouterdebie** [comment]
Absolutely not! I'll check with @ravwojdyla if we can merge. 

// Wouter

Fatfingered on an iPhone

**Comment by wouterdebie** [comment]
I guess this is solved!

**Comment by thale013** [comment]
Need help?  Happy to jump in on this one - could really use this feature

**Comment by bolkedebruin** [comment]
@thale013 it is merged already and works for authentication. Encryption is not covered yet.

**Comment by thale013** [comment]
@bolkedebruin  I'm trying to get this deployed on a SASL/GSSAPI/Kerberos cluster running CDH 5.3.3 and seem to be having trouble with basic ls command (i.e. "snakebite ls /").  This returns "Found 0 Items" and I'm not really sure how to interpret the debug output quite yet (still getting my feet wet with snakebite).  Any suggestions?

**Comment by chenbensong** [comment]
@thale013 this sounds like the same experience I had at https://github.com/spotify/snakebite/pull/153#issuecomment-121290538
Need to address RPC encryption which bolkedebruin might do very soon :)
To see if this is the case for your environment, search for rpc-protection in your hadoop and hdfs config xml.

**Comment by bolkedebruin** [comment]
@thale013 please check above suggestion. Hopefully I will have some time to look at it this month.

**Comment by thale013** [comment]
looks like rpc-protection is set to privacy :(

@bolkedebruin - I'd like to help if I can, but not sure where to start.  Thoughts?

**Comment by pug2694328** [comment]
Trying to get this to work against our cluster and hitting an error.  Perhaps we need to change something on the cluster configuration?
I have a valid kerberos ticket verified by using the hdfs cli.

Using the [forked version] https://github.com/bolkedebruin/snakebite
<addr>
from snakebite.client import Client

client = Client(use_sasl=True
                ,host="<namenode host>"
                ,port=<namenode rpc port>
)

for x in client.ls(['/']):
    print x

Hits this error:
  File "/Users/<uname>/.virtualenvs/hadoop_tools/lib/python2.7/site-packages/snakebite/channel.py", line 407, in handle_error
    raise RequestError("\n".join([header.exceptionClassName, header.errorMsg]))
snakebite.errors.RequestError: org.apache.hadoop.security.AccessControlException
KERBEROS authentication is not enabled.  Available:[TOKEN, KERBEROS]
</addr>

Any ideas what might be the problem?

**Comment by bolkedebruin** [comment]
@pug2694328 I'm not sure, btw the official snakebite has my patches as well so you could try that one (however they should be the same). I am diving in next week again and can have a look again. Can you share some details about your kerberos setup? auth only or also privacy?

**Comment by pug2694328** [comment]
This is solved.  It appears the namenode hostname must be fully qualified.
I was passing just 'host', where I should have been passing 'host.<domain>.intra'.
Works like a charm now and thanks @bolkedebruin I'm now using the official version.

**Comment by bolkedebruin** [comment]
@thale013 @chenbensong implementing something else than "auth" will be taking a little bit longer. The patch looks to be a bit more invasive due to the fact the input stream and output stream need to be wrapped. This requires some changes in the way snakebite handles this currently.

**Comment by hsaputra** [comment]
Hi All. Any release already containing this change?

**Comment by bolkedebruin** [comment]
For a long time...

**Comment by hsaputra** [comment]
Ah, thanks, I should have read the year this issue is closed more carefully =(
Sorry for commenting up on old issue

**Comment by davidsunnykondru** [comment]
> @thale013 @chenbensong implementing something else than "auth" will be taking a little bit longer. The patch looks to be a bit more invasive due to the fact the input stream and output stream need to be wrapped. This requires some changes in the way snakebite handles this currently.
